import './globals.css'
import './components/header.module.css';

import Header from '@/app/components/Header'
import { Nunito } from 'next/font/google'

const nunito = Nunito({
  weight: ['300', '600', '800'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
